# Generated by Django 3.2.6 on 2021-08-13 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Talks',
            fields=[
                ('talk_id', models.AutoField(primary_key=True, serialize=False)),
                ('talk_title', models.CharField(max_length=1500)),
                ('talk_author', models.CharField(max_length=500)),
                ('talk_href', models.CharField(max_length=1000)),
                ('talk_image', models.CharField(max_length=500)),
            ],
        ),
    ]
